### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by tlnagy** [Rory-Finnegan/Playground.jl#19]
Are you planning on eventually distributing binaries of `Playground` so that the user doesn't have to mess around with getting julia set up before making virtual environments?

**Comment by Rory-Finnegan** [comment]
I hadn't really though about it, but I guess now that it's building executables I don't see any reason not to.

**Comment by Rory-Finnegan** [comment]
I looked into this briefly, but it looks like `build_executable` doesn't currently bundle julia and its dependencies into the executable directory and instead hard codes the rpath to the host julia install directory. I've opened an issue [here](https://github.com/dhoegh/BuildExecutable.jl/issues/11) if anyone is interested.
