### ISSUE TITLE
'playground activate' under zsh fails with "no such option: rcfile"

### ISSUE THREAD

**Issue by rdeits** [Rory-Finnegan/Playground.jl#39]
Attempting to activate a playground when using the zsh shell gives:

```bash
/bin/zsh: no such option: rcfile
ERROR: LoadError: failed process: Process(`/bin/zsh --rcfile /Users/rdeits/locomotion/explorations/point-cloud-signed-distance/pkg/zshrc`, ProcessExited(1)) [1]
 in run at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_shell at /Users/rdeits/.julia/v0.4/Playground/src/activate.jl:61
 in activate at /Users/rdeits/.julia/v0.4/Playground/src/activate.jl:19
 in main at /Users/rdeits/.julia/v0.4/Playground/src/Playground.jl:74
 in main at /Users/rdeits/.julia/v0.4/Playground/src/Playground.jl:41
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/rdeits/.playground/bin/playground, in expression starting on line 10
```

As far as I can tell, there's no easy way to force zsh to use an arbitrary file instead of its `.zshrc` file. It is possible to overwrite `ZDOTDIR`, which is where zsh looks for a file named `.zshrc`, but that may have other consequences since other files are also expected in that location (from `man zsh`): 

```
$ZDOTDIR/.zshenv
$ZDOTDIR/.zprofile
$ZDOTDIR/.zshrc
$ZDOTDIR/.zlogin
$ZDOTDIR/.zlogout
```

Perhaps instead of duplicating and appending to the user's base `.zshrc` file, it would be better not to duplicate the content of that file, but instead just put the playground-specific lines into a file and invoke the shell as:

```bash
zsh -c "source /path/to/playground/file; zsh -i" 
```

**Comment by Rory-Finnegan** [comment]
That's in fact how this was fixed in commit [7ca1b89](https://github.com/Rory-Finnegan/Playground.jl/commit/7ca1b8957675d06d797393677506fc479208d501) on master, I just haven't gotten around to pulling those fixes back into dev.

**Comment by rdeits** [comment]
Great! I imagine this also makes #40 irrelevant as well?

**Comment by Rory-Finnegan** [comment]
For now we're just special casing zsh as I'd prefer to explicitly pass the rc file whenever possible, but I may change this later as I don't really like special casing either.

**Comment by Rory-Finnegan** [comment]
It was kind of ugly, but I've synced the fixes from master into dev. Both of your issues should be resolved now.

**Comment by rdeits** [comment]
Awesome, thanks!
