### ISSUE TITLE
When ~/.bashrc or ~/.zshrc is a symlink, `playground activate` modifies the original file

### ISSUE THREAD

**Issue by rdeits** [Rory-Finnegan/Playground.jl#40]
`playground activate` calls `run_shell()`, which tries to duplicate the user's rcfile before modification:

```julia
usr_rc = joinpath(homedir(), "." * basename(ENV["SHELL"]) * "rc")
pg_rc = joinpath(dirname(ENV["JULIA_PKGDIR"]), basename(ENV["SHELL"]) * "rc")

if !ispath(pg_rc)
    cp(usr_rc, pg_rc)
```

but if `usr_rc` is a symlink, then `pg_rc` is also a symlink to that same original file. That means that when we write to `pg_rc`, we actually overwrite the user's rcfile in `~/.bashrc` or `~/.zshrc`. 

I believe the fix is just to add `follow_symlinks=true` to the call to `cp()`.

**Comment by Rory-Finnegan** [comment]
#41 merged into dev.
